### ISSUE TITLE
if $namevar exists in ssl_multi_cert.config no changes are made

### ISSUE THREAD

**Issue by igalic** [Brainsware/puppet-trafficserver#18]
```puppet
trafficserver_ssl_multicert { 'ease.at.pem':
  ensure       => 'present',
  ssl_key_name => 'ease.at.key',
}

trafficserver_ssl_multicert { 'coffee.platform.pem':
  ensure       => 'present',
  ssl_key_name => 'ease.at.key',
}
```

creates a file with:

```
ssl_cert_name=ease.at.pem ssl_key_name => 'ease.at.key',
ssl_cert_name=coffee.platform ssl_key_name => 'ease.at.key',
```

now changing that manifest to:

```puppet
trafficserver_ssl_multicert { 'ease.at.pem':
  ensure       => 'present',
  ssl_key_name => 'ease.at.key',
  ssl_ca_name  => 'startssl.class2.pem'
}
```

does nothing.

**Comment by igalic** [comment]
the same is probably true for `plugin.config` but i haven't dared looking at that yet :(

i'm pretty and sure i'll have to rewrite this whole mess to use @adrienthebo's filemapper, sooner rather than later.

**Comment by ffrank** [comment]
I think this is a fundamental problem with your management approach.

With parsedfile, each `resource` should be represented by one line in the managed file. (`cron` is a notable exception, where multiple lines can contribute to a resource, but please for the love of god - avoid that.)

Is `ssl_multicert` a singleton resource? Can there be more than one in a given system?

If not, then this should likely be no resource type whatsoever. I would go for a parameterized class. Implement using `concat`.

**Comment by igalic** [comment]
yes. each line represents a separate resource. (i've updated the initial description to reflect that)
***
i think the primary reason for using parsedfile to begin with is so as to be able to use `puppet resource` on the command line. that is a tremendously useful feature imo, and it's a bit sad it's only available to types & providers.

**Comment by ffrank** [comment]
...uuuund das war mir auch voll vom Tisch gerutscht.

Ich bin aber neugierig. Das könnte ein esoterischer Fehler in `parsedfile` sein (schockierend, ich weiß). Zum Codemobil!

**Comment by igalic** [comment]
danke recht herzlich, @ffrank!
****
so, it would appear, the *only* thing missing is to re-document this module and add tests.
but, tests in puppet are still made of sadness, and rspec-puppet, so i'm not sure what to think of that :|

**Comment by ffrank** [comment]
I would go and try to mimick unit tests of other `parsedfile` providers.
